package com.ecommerce.metier;
// Generated Nov 1, 2022, 6:01:03 PM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie implements java.io.Serializable {

	private int idcat;
	private String libelle;
	private String description;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Categorie() {
	}

	public Categorie(int idcat) {
		this.idcat = idcat;
	}

	public Categorie(int idcat, String libelle, String description, Set<Produit> produits) {
		this.idcat = idcat;
		this.libelle = libelle;
		this.description = description;
		this.produits = produits;
	}

	public int getIdcat() {
		return this.idcat;
	}

	public void setIdcat(int idcat) {
		this.idcat = idcat;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
