package com.ecommerce.metier;
// Generated Nov 1, 2022, 6:01:03 PM by Hibernate Tools 3.6.2.Final

import java.util.Date;

/**
 * Commentaire generated by hbm2java
 */
public class Commentaire implements java.io.Serializable {

	private int idComm;
	private Produit produit;
	private Integer idcmd;
	private String commentaire;
	private Date datePub;

	public Commentaire() {
	}

	public Commentaire(int idComm) {
		this.idComm = idComm;
	}

	public Commentaire(int idComm, Produit produit, Integer idcmd, String commentaire, Date datePub) {
		this.idComm = idComm;
		this.produit = produit;
		this.idcmd = idcmd;
		this.commentaire = commentaire;
		this.datePub = datePub;
	}

	public int getIdComm() {
		return this.idComm;
	}

	public void setIdComm(int idComm) {
		this.idComm = idComm;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Integer getIdcmd() {
		return this.idcmd;
	}

	public void setIdcmd(Integer idcmd) {
		this.idcmd = idcmd;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Date getDatePub() {
		return this.datePub;
	}

	public void setDatePub(Date datePub) {
		this.datePub = datePub;
	}

}
