package com.ecommerce.metier;
// Generated Nov 1, 2022, 6:01:03 PM by Hibernate Tools 3.6.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private String login;
	private String mdp;
	private String role;
	private String question;
	private String reponse;
	private Date dateCreation;
	private Set<Client> clients = new HashSet<Client>(0);

	public Compte() {
	}

	public Compte(String login) {
		this.login = login;
	}

	public Compte(String login, String mdp, String role, String question, String reponse, Date dateCreation,
			Set<Client> clients) {
		this.login = login;
		this.mdp = mdp;
		this.role = role;
		this.question = question;
		this.reponse = reponse;
		this.dateCreation = dateCreation;
		this.clients = clients;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
