package com.ecommerce.metier;
// Generated Nov 1, 2022, 6:01:03 PM by Hibernate Tools 3.6.2.Final

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private int idimg;
	private String url;
	private Integer isprincipal;
	private Integer idp;

	public Image() {
	}

	public Image(int idimg) {
		this.idimg = idimg;
	}

	public Image(int idimg, String url, Integer isprincipal, Integer idp) {
		this.idimg = idimg;
		this.url = url;
		this.isprincipal = isprincipal;
		this.idp = idp;
	}

	public int getIdimg() {
		return this.idimg;
	}

	public void setIdimg(int idimg) {
		this.idimg = idimg;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getIsprincipal() {
		return this.isprincipal;
	}

	public void setIsprincipal(Integer isprincipal) {
		this.isprincipal = isprincipal;
	}

	public Integer getIdp() {
		return this.idp;
	}

	public void setIdp(Integer idp) {
		this.idp = idp;
	}

}
