package com.ecommerce.metier;
// Generated Nov 1, 2022, 6:01:03 PM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Wishlist generated by hbm2java
 */
public class Wishlist implements java.io.Serializable {

	private int idw;
	private Client client;
	private String libelle;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Wishlist() {
	}

	public Wishlist(int idw) {
		this.idw = idw;
	}

	public Wishlist(int idw, Client client, String libelle, Set<Produit> produits) {
		this.idw = idw;
		this.client = client;
		this.libelle = libelle;
		this.produits = produits;
	}

	public int getIdw() {
		return this.idw;
	}

	public void setIdw(int idw) {
		this.idw = idw;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
